# Generated by Django 2.2.12 on 2020-11-01 13:34

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Original filepath')),
                ('modifiedat', models.DateTimeField(verbose_name='Original file modification date')),
                ('layer_type', models.CharField(choices=[('STRING', 'STRING'), ('GEOJSON', 'GEOJSON'), ('XYZ', 'XYZ')], max_length=7, verbose_name='Layer type')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon')),
                ('rel_url', models.URLField(max_length=400, verbose_name='Layer URL')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Layer options')),
                ('description', models.TextField(null=True, verbose_name='Layer description')),
                ('released', models.BooleanField(default=False, verbose_name='Released')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End date')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Layer name')),
            ],
        ),
    ]
