# Generated by Django 2.2.12 on 2020-10-28 13:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, unique=True, verbose_name='Original filename')),
                ('modified', models.DateTimeField(verbose_name='File modification date')),
                ('abs_url', models.URLField(max_length=400, verbose_name='File absolute URL')),
                ('type', models.CharField(choices=[('STRING', 'STRING'), ('GEOJSON', 'GEOJSON'), ('TMS', 'TMS'), ('XYZ', 'XYZ')], max_length=7, verbose_name='Layer type')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon')),
                ('rel_url', models.URLField(max_length=400, verbose_name='Relative domain URL')),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Layer properties')),
                ('description', models.TextField(null=True, verbose_name='Layer description')),
                ('released', models.BooleanField(default=False, verbose_name='Released')),
                ('start', models.DateField(verbose_name='Start date')),
                ('end', models.DateField(verbose_name='End date')),
                ('name', models.CharField(max_length=200, verbose_name='Layer name')),
            ],
        ),
    ]
