# Generated by Django 2.2.12 on 2020-10-30 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='end',
        ),
        migrations.RemoveField(
            model_name='results',
            name='start',
        ),
        migrations.AddField(
            model_name='results',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='results',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='results',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Layer name'),
        ),
    ]
