# Generated by Django 2.2.12 on 2020-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20201030_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='filename',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Original filename'),
        ),
    ]
