# Generated by Django 3.1 on 2020-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='AOI description'),
        ),
    ]
