# Generated by Django 3.1 on 2020-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_aoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='layer_type',
            field=models.CharField(choices=[('GEOJSON', 'GEOJSON'), ('MVT', 'MVT'), ('XYZ', 'XYZ')], max_length=7, verbose_name='Layer type'),
        ),
    ]
