# Generated by Django 3.1 on 2020-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_auto_20201130_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AoI',
        ),
    ]
