# Generated by Django 3.1 on 2020-12-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_delete_aoi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='polygon',
            new_name='bounding_polygon',
        ),
    ]
