# Generated by Django 3.1 on 2020-12-07 16:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_auto_20201207_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='bounding_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Bounding polygon'),
        ),
    ]
