# Generated by Django 3.1 on 2021-01-20 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0006_add_models_db_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0012_auto_20210114_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aoi.request', verbose_name="Client's request id"),
        ),
    ]
