# Generated by Django 3.1 on 2021-01-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_rename_acl_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acl',
            options={'ordering': ['user'], 'verbose_name': 'Access Control List', 'verbose_name_plural': 'Access Control Lists'},
        ),
    ]
