# Generated by Django 3.1 on 2023-02-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0019_result_colormap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-modifiedat'], 'permissions': (('delete_any_result', 'Can delete any result'),), 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
    ]
