# Generated by Django 3.1 on 2023-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0019_result_colormap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-modifiedat'], 'permissions': (('delete_result_admin', 'Can delete result as admin'),), 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
    ]
