# Generated by Django 3.1 on 2025-03-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0021_result_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='validation_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation End date'),
        ),
        migrations.AddField(
            model_name='result',
            name='validation_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation start date'),
        ),
    ]
