# Generated by Django 3.1 on 2026-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0022_auto_20250321_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='layer_type',
            field=models.CharField(choices=[('GEOJSON', 'GEOJSON'), ('MVT', 'MVT'), ('XYZ', 'XYZ'), ('JSON', 'JSON')], max_length=7, verbose_name='Layer type'),
        ),
    ]
