# Generated by Django 3.1 on 2026-04-28 10:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0023_auto_20260403_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='bounding_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Bounding polygon'),
        ),
    ]
