apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: sip
spec:
  selector:
    app: sip
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: sip
  labels:
    app: sip
    tier: frontend
spec:
  selector:
    matchLabels:
      app: sip
      tier: frontend
  template:
    metadata:
      labels:
        app: sip
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: registry.quantumobile.co/sip-web-server:latest
        imagePullPolicy: "IfNotPresent"
        # resources:
        #   limits:
        #     memory: "2048Mi"
        #     cpu: "2048m"
        env:
          - name: MAPBOX_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: sip-secret
                key: MAPBOX_ACCESS_TOKEN
        envFrom:
              - configMapRef:
                  name: app-config
        ports:
        - containerPort: 80
          name: frontend
        volumeMounts:
          - mountPath: /data
            name: sip-data-storage
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: sip-data-storage
          persistentVolumeClaim:
            claimName: sip-data-pvc
