apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: prod
  labels:
    app: sip
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort:  31080
      protocol: TCP
      name: http
  selector:
    app: sip
    tier: frontend