version: "3.5"
services:

  db:
    image: postgis/postgis:13-3.0
    volumes:
      - /home/quantum/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    networks:
      - sip
    restart: on-failure

  webapplication:
    image: registry.quantumobile.co/portal_soilmate_webapplication
    volumes:
      - ../data:/data
      - ../data/media:/media
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings-prod
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    command: /bin/bash -c "exec invoke run-prod"
    depends_on:
      - db
    networks:
      - sip
    restart: on-failure

  webserver:
    image: registry.quantumobile.co/portal_soilmate_webserver
    volumes:
      - ../data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapplication
    networks:
      - sip
    restart: on-failure

  # https://github.com/bokysan/docker-postfix#relaying-messages-through-google-apps-account
  smtp:
    image: boky/postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=portal.soilmate.ai
      - RELAYHOST=smtp-relay.gmail.com:587
    networks:
      - sip

networks:
  sip:
