version: "3"
services:
  run_notebook:
    build:
      context: ./jupyter/example
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/jovyan/work
#      - ./jupyter/code:/home/jovyan/work/code
    environment:
      - JUPYTER_ENABLE_LAB=yes
