version: "3.5"
services:

  db:
    image: postgis/postgis:13-3.0
    volumes:
      - /home/quantum/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    networks:
      - sip

  webapplication:
    build:
      context: ./webapplication
      dockerfile: prod.Dockerfile
    volumes:
      - /home/quantum/sip:/data
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings-prod
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    command: /bin/bash -c "exec invoke run-prod"
    depends_on:
      - db
    networks:
      - sip

  webserver:
    build:
      context: ./
      dockerfile: ./webserver/prod.Dockerfile
    volumes:
      - /home/quantum/sip:/data
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - webapplication
    networks:
      - sip
    env_file:
      - /home/quantum/webserver.env

networks:
  sip:
