version: "3"
services:
  db:
    image: postgis/postgis:13-3.0
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=eiJ2koo6

  webapplication:
    build:
      context: ./webapplication
      dockerfile: dev.Dockerfile
      args:
        - UID
        - GID
    restart: always
    command: /bin/bash -c "exec invoke rundev"
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=eiJ2koo6
    env_file:
      - .env
    volumes:
      - ./webapplication:/code
    expose:
      - 9000
    ports:
      - "9001:9000"
    depends_on:
      - db
      - webserver

  webviewer:
    image: node:14.5.0
    volumes:
      - ./webviewer:/client
    working_dir: /client
    expose:
      - 3000
    ports:
      - "3001:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - webserver

  webserver:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./webserver/dev.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data
    expose:
      - 8082
    ports:
      - "8082:8082"
#    depends_on:
#      - webapplication

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
