version: "3.5"
services:

  db:
    image: postgis/postgis:13-3.0
    volumes:
      - ../geoap_data_files/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=eiJ2koo6
    networks:
      - sip
    restart: on-failure

  webapplication:
    image: registry.quantumobile.co/geoap_webapplication
    volumes:
      - ./webapplication:/code
      - ../geoap_data:/data
      - ../geoap_data/media:/media
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings-remote
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=eiJ2koo6
    command: /bin/bash -c "exec invoke run-prod"
    depends_on:
      - db
    networks:
      - sip
    restart: on-failure

  webserver:
    image: registry.quantumobile.co/geoap_remote_webserver
    volumes:
      - ../geoap_data:/data
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - webapplication
    networks:
      - sip
    restart: on-failure

networks:
  sip:
