version: "3.5"
services:

  db:
    image: postgres:10.12
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    networks:
      - sip

  webapplication:
    build:
      context: ./webapplication
      dockerfile: prod.Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings-prod
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    command: /bin/bash -c "exec invoke run-prod"
    depends_on:
      - db
    networks:
      - sip

  webserver:
    build:
      context: ./
      dockerfile: ./webserver/prod.Dockerfile
    volumes:
      - ../data:/data
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - webapplication
    networks:
      - sip

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - sip
  
networks:
  sip:
