
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapbox-cache-volumeclaim
  namespace: sip
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi