apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  namespace: prod
spec:
  selector:
    matchLabels:
      app: web-application
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-application
        tier: backend
    spec:
      containers:
        - name: web-application
          image: registry.quantumobile.co/sip-web-application:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          command: ['/bin/bash', '-c', 'exec invoke run-prod']
          ports:
          - containerPort: 9000
            name: web-application
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sip-secret
                  key: postgresname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sip-secret
                  key: postgrespassword
          envFrom:
              - configMapRef:
                  name: app-config
          volumeMounts:
              - name: sip-data-volume
                mountPath: /data
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: sip-data-volume
          persistentVolumeClaim:
            claimName: sip-data-volumeclaim   
