
apiVersion: v1
kind: Service
metadata:
  name: webapplication
  namespace: sip
  labels:
    app: web-application
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: webapplication
  selector:
    app: web-application
    tier: backend