
apiVersion: v1
kind: Service
metadata:
  name: web-application
  namespace: prod
  labels:
    app: web-application
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: web-application
    tier: backend