apiVersion: v1
kind: Service
metadata:
  name: web-application-nodeport
  namespace: prod
  labels:
    app: sip
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort:  31090
      protocol: TCP
      name: http
  selector:
    app: web-application
    tier: backend
