apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sip-data-volumeclaim
  namespace: prod
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi