apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  POSTGRES_DB: sip_db
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DJANGO_SETTINGS_MODULE: sip.settings-prod
  MAPBOX_ACCESS_TOKEN: ""

