apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  POSTGRES_DB: sip_db
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DJANGO_SETTINGS_MODULE: sip.settings-prod
  MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoiZG1pdHJpMTcxMCIsImEiOiJjbDg5cjh2ZGIwOXBmM3BuMzc5eTZvYjVqIn0.2C9wKShhjjcNckf3mxR7OQ"
  SIP_PROD_ENV: "k8s"