kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: ./data
      containerPath: /data
    - hostPath: ./db
      containerPath: /db
  extraPortMappings:
  - containerPort: 31080
    hostPort: 31080
    protocol: TCP