apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sip-data-pvc
  namespace: sip-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
