apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sip-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.37
    path: "/home/dyman/Projects/quantum/sip/data" # TODO
    readOnly: false
