apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sip-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.34
    path: "/home/sip/sip_data"
    readOnly: false
