kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-sip-data-pvc
  namespace: sip-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
