kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-hostpath-pv
  namespace: sip-prod
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db"