kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-hostpath-pvc
  namespace: sip-prod
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi