apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-robot
  namespace: sip-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-robot
  namespace: sip-prod
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-robot
  namespace: sip-prod
subjects:
  - kind: ServiceAccount
    name: job-robot # Name of the ServiceAccount
    namespace: sip-prod
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: job-robot # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io