apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sip-ingress
  namespace: sip-prod
spec:
  rules:
  - host: soilmate.example.com  # TODO
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: webserver
              port:
                number: 80