# Generated by Django 3.1 on 2020-12-04 08:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AoI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Aoi name')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon')),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Area of interest',
                'verbose_name_plural': 'Areas of interest',
                'ordering': ['name'],
            },
        ),
    ]
