# Generated by Django 3.1 on 2021-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Jupyter Notebook name')),
                ('base_url', models.URLField(max_length=400, verbose_name='Base url')),
                ('password', models.CharField(max_length=128)),
                ('path_to_a_notebook', models.CharField(max_length=200, unique=True, verbose_name='Path to a notebook')),
                ('kernel_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Jupyter Notebook',
                'verbose_name_plural': 'Jupyter Notebooks',
                'ordering': ['name'],
            },
        ),
    ]
