# Generated by Django 3.1 on 2021-01-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Jupyter Notebook name')),
                ('image', models.CharField(max_length=400, verbose_name='Image')),
                ('path_to_a_notebook', models.CharField(max_length=200, unique=True, verbose_name='Path to a notebook')),
                ('kernel_name', models.CharField(blank=False, max_length=200, null=False, verbose_name='Kernel name')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Is validated')),
            ],
            options={
                'verbose_name': 'Jupyter Notebook',
                'verbose_name_plural': 'Jupyter Notebooks',
                'ordering': ['name'],
            },
        ),
    ]
