# Generated by Django 3.1 on 2021-01-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aoi', '0002_jupyternotebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('error', models.CharField(blank=True, max_length=400, null=True, verbose_name='Error')),
                ('aoi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoi.aoi', verbose_name='Aoi name')),
                ('jupyter_notebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoi.jupyternotebook', verbose_name='Jupyter notebook name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
    ]
