# Generated by Django 3.1 on 2021-01-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0003_request'),
        ('aoi', '0003_aoi_user_id'),
    ]

    operations = [
    ]
