# Generated by Django 3.1 on 2021-01-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0004_merge_20210115_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jupyternotebook',
            old_name='path_to_a_notebook',
            new_name='path',
        ),
    ]
