# Generated by Django 3.1 on 2021-01-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0005_rename_notebook_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aoi',
            old_name='user_id',
            new_name='user',
        ),
    ]
