# Generated by Django 3.1 on 2021-01-20 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aoi', '0005_rename_notebook_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='aoi', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='aoi_id',
            field=models.ForeignKey(db_column='aoi_id', on_delete=django.db.models.deletion.PROTECT, to='aoi.aoi', verbose_name='Aoi name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='jupyter_notebook_id',
            field=models.ForeignKey(db_column='jupyter_notebook_id', on_delete=django.db.models.deletion.PROTECT, to='aoi.jupyternotebook', verbose_name='Jupyter notebook name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User name'),
        ),
    ]
