# Generated by Django 3.1 on 2021-01-22 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aoi', '0007_rename_request_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='AOI name'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoi', to=settings.AUTH_USER_MODEL, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='jupyternotebook',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Notebook name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='aoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aoi.aoi', verbose_name='AOI id'),
        ),
        migrations.AlterField(
            model_name='request',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aoi.jupyternotebook', verbose_name='Notebook id'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User id'),
        ),
    ]
