# Generated by Django 3.1 on 2021-02-15 18:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0009_add_success_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='request',
            name='aoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aoi.aoi', verbose_name='AOI id'),
        ),
        migrations.RunSQL("""
        UPDATE aoi_request SET polygon=(SELECT aoi_aoi.polygon FROM aoi_aoi WHERE aoi_request.aoi_id=aoi_aoi.id);
        """),
        migrations.AlterField(
            model_name='request',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=False, srid=4326, verbose_name='Polygon'),
        ),
    ]
