# Generated by Django 3.1 on 2021-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0011_request_add_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='calculated',
            field=models.BooleanField(default=False, verbose_name='Notebook calculated'),
        ),
        migrations.RunSQL("""
        UPDATE aoi_request SET calculated=TRUE WHERE aoi_request.success=TRUE;
        """),
        migrations.AlterField(
            model_name='request',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Execution succeeded'),
        ),
    ]
