# Generated by Django 3.1 on 2021-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0013_request_add_run_validation_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
    ]
