# Generated by Django 3.1 on 2021-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0013_request_add_run_validation_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='AoiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='AOI type name')),
                ('description', models.TextField(blank=True, default='', verbose_name='AOI type description')),
            ],
            options={
                'verbose_name': 'Area of interest type',
                'verbose_name_plural': 'Areas of interest types',
                'db_table': 'aoi_aoi_type',
                'ordering': ['name'],
            },
        ),
    ]
