# Generated by Django 3.1 on 2021-07-06 16:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0013_request_add_run_validation_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotBoundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoi.aoi', verbose_name='AOI id')),
            ],
        ),
    ]
