# Generated by Django 3.1 on 2021-07-27 06:22

from django.db import migrations


def add_aoi_types(apps, schema_editor):
    aoi_types = apps.get_model('aoi', 'AoiType')
    aoi_types_data = [
        {'name': 'user_defined', 'description': 'Area of interest defined by user.'},
        {'name': 'field_boundaries', 'description': 'Area of interest created by user request using field boundaries'}
    ]
    aoi_types_list = []
    for aoi_type in aoi_types_data:
        if not aoi_types.objects.filter(name=aoi_type['name']):
            aoi_types_list.append(aoi_types(name=aoi_type['name'], description=aoi_type['description']))
    db_alias = schema_editor.connection.alias
    aoi_types.objects.using(db_alias).bulk_create(aoi_types_list)
            
    
class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0014_aoi_type'),
    ]

    operations = [
        migrations.RunPython(add_aoi_types)
    ]
