# Generated by Django 3.1 on 2022-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0018_remove_AOI_type_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyternotebook',
            name='additional_parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional parameters'),
        ),
        migrations.AddField(
            model_name='request',
            name='additional_parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional parameters'),
        ),
    ]
