# Generated by Django 3.1 on 2022-04-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0019_jupyternotebook_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Optional parameters'),
        ),
    ]
