# Generated by Django 3.1 on 2022-06-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0020_jupyternotebook_run_on_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyternotebook',
            name='period_required',
            field=models.BooleanField(default=True, verbose_name='Start and end dates are requaired'),
        ),
    ]
