# Generated by Django 3.1 on 2022-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0021_jupyternotebook_period_requaired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('FLOAT', 'Float'), ('BOOL', 'Boolean'), ('LIST', 'List'), ('DATE', 'Date')], default='STR', max_length=10, verbose_name='Type')),
                ('assigned_from', models.CharField(choices=[('settings', 'Global settings'), ('user', 'User attributes'), ('request', 'Request attributes'), ('component', 'Another component')], default='request', max_length=20, verbose_name="Attribute's origin")),
                ('is_file', models.BooleanField(default=False, verbose_name='Is it a file?')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_error', models.BooleanField(default=False, verbose_name='Is error output?')),
            ],
        ),
        migrations.AlterField(
            model_name='jupyternotebook',
            name='period_required',
            field=models.BooleanField(default=True, verbose_name='Start and end dates are required'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.CharField(max_length=255, verbose_name='Image tag')),
                ('command', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Command')),
                ('require_GPU', models.BooleanField(default=False, verbose_name='Whether GPU is needed for a component to run')),
                ('run_validation', models.BooleanField(default=False, verbose_name='Run validation')),
                ('success', models.BooleanField(default=False, verbose_name='Validation succeeded')),
                ('inputs', models.ManyToManyField(to='aoi.Input')),
                ('outputs', models.ManyToManyField(to='aoi.Output')),
            ],
        ),
    ]
