# Generated by Django 3.1 on 2022-11-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0022_auto_20221117_1755'),
    ]

    operations = [
        migrations.RenameModel('jupyternotebook', 'component'),
        migrations.RenameField('request','notebook', 'component'),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['name'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterField(
            model_name='request',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aoi.component', verbose_name='Request id'),
        ),
    ]
