# Generated by Django 3.1 on 2022-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0022_auto_20221112_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
