# Generated by Django 3.1 on 2023-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0025_component_validation_pernissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='scihub_creds_required',
            field=models.BooleanField(default=False, verbose_name='Copernicus Open Access Hub credentials are required'),
        ),
        migrations.AddField(
            model_name='component',
            name='sentinel1_aws_creds_required',
            field=models.BooleanField(default=False, verbose_name='Sentinel 1 AWS credentials are required'),
        ),
        migrations.AddField(
            model_name='request',
            name='notify_user',
            field=models.BooleanField(default=False, verbose_name='Notify of the result'),
        ),
    ]
