# Generated by Django 3.1 on 2023-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0026_additional_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Basic Price (per 1.sq.km)'),
        ),
    ]
