# Generated by Django 3.1 on 2023-01-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0026_additional_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notify_user',
            field=models.BooleanField(default=False, verbose_name='Notify of the result'),
        ),
    ]
