# Generated by Django 3.1 on 2023-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0027_component_basic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='date_type',
            field=models.IntegerField(choices=[(1, 'YEAR'), (2, 'DATE RANGE'), (3, 'SEASON')], default=2),
        ),
    ]
