# Generated by Django 3.1 on 2023-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0028_component_date_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='name',
            field=models.CharField(max_length=200, verbose_name='AOI name'),
        ),
    ]
