# Generated by Django 3.1 on 2023-02-27 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aoi', '0029_auto_20230224_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='name',
            field=models.CharField(max_length=200, verbose_name='AOI name'),
        ),
        migrations.AlterUniqueTogether(
            name='aoi',
            unique_together={('user', 'name')},
        ),
    ]
