# Generated by Django 3.1 on 2023-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0030_changed_unique_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='separate_cache_folder',
            field=models.BooleanField(default=False, verbose_name='Separate cache folder for each request required'),
        ),
    ]
