# Generated by Django 3.1 on 2023-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0030_changed_unique_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='api_endpoint_required',
            field=models.BooleanField(default=False, verbose_name='API endpoint is required'),
        ),
        migrations.AddField(
            model_name='component',
            name='user_key_required',
            field=models.BooleanField(default=False, verbose_name='User key is required'),
        ),
    ]
