# Generated by Django 3.1 on 2023-04-21 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0031_component_geoap_creds_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='component',
            name='description_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Description picture'),
        ),
        migrations.AddField(
            model_name='component',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=8, verbose_name='Domains'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.CharField(max_length=400, verbose_name='Docker Image'),
        ),
    ]
