# Generated by Django 3.1 on 2023-06-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0032_auto_20230421_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_origin',
            field=models.CharField(default='https://portal.soilmate.ai/', max_length=50, verbose_name='Request origin'),
        ),
    ]
