# Generated by Django 3.1 on 2023-06-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0033_request_request_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsCommentErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_readable_error', models.CharField(blank=True, max_length=400, null=True, verbose_name='User-readable Error Message')),
                ('original_component_error', models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Original component "error" example')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user_error',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='User Error'),
        ),
    ]
