# Generated by Django 3.1 on 2023-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0033_request_request_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_error', models.CharField(blank=True, max_length=400, null=True, verbose_name='User error')),
                ('component_error', models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Component error')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user_error',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='User Error'),
        ),
    ]
