# Generated by Django 3.1 on 2023-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0033_request_request_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='available_dates',
            field=models.JSONField(blank=True, null=True, verbose_name='Available dates'),
        ),
    ]
