# Generated by Django 3.1 on 2023-09-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0034_aoi_sentinel_hub_available_dates'),
        ('aoi', '0034_auto_20230630_0904'),
    ]

    operations = [
    ]
