# Generated by Django 3.1 on 2023-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0034_aoi_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='sentinel_image_type',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Sentinel-1'), (3, 'Sentinel-2')], default=1),
        ),
    ]
