# Generated by Django 3.1 on 2023-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0035_merge_20230913_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='sentinel_hub_available_dates_update_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Sentinel Hub available dates update time'),
        ),
        migrations.AddField(
            model_name='component',
            name='sentinel_image_type',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Sentinel-1'), (3, 'Sentinel-2'), (4, 'Sentinel-1 & Sentinel-2')], default=1),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='sentinel_hub_available_dates',
            field=models.JSONField(blank=True, null=True, verbose_name='Available dates from Sentinel Hub'),
        ),
    ]
