# Generated by Django 3.1 on 2024-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0036_component_detail_description_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='google_bucket_input_data',
            field=models.BooleanField(default=False, verbose_name='Google bucket input data'),
        ),
    ]
