# Generated by Django 3.1 on 2023-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0036_component_detail_description_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionErrorMessage',
        ),
    ]
