# Generated by Django 3.1 on 2024-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0037_component_google_bucket_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='additional_parameter2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Additional parameter2'),
        ),
    ]
