# Generated by Django 3.1 on 2024-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0038_component_additional_parameter2'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additional_parameter2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Additional parameter2'),
        ),
    ]
