# Generated by Django 3.1 on 2024-09-04 09:53

from django.db import migrations, models


def calculate_square_in_km(apps, schema_editor):
    AoI = apps.get_model('aoi', 'AoI')
    for aoi in AoI.objects.all():
        if aoi.polygon:
            transformed_polygon = aoi.polygon.transform(6933, clone=True)
            aoi.square_in_km = round((transformed_polygon.area / 1_000_000), 8)
            aoi.save()


class Migration(migrations.Migration):
    dependencies = [
        ('aoi', '0039_request_additional_parameter2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='square_in_km',
            field=models.FloatField(default=0, verbose_name='AoI square in km'),
        ),
        migrations.RunPython(calculate_square_in_km),
    ]
