# Generated by Django 3.1 on 2024-11-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0040_aoi_square_in_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='additional_parameter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional parameter'),
        ),
    ]
