# Generated by Django 3.1 on 2024-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0041_auto_20241101_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additional_parameter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional parameter'),
        ),
    ]
