# Generated by Django 3.1 on 2025-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0042_auto_20241101_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='average_calculation_time_per_km2',
            field=models.IntegerField(default=0, verbose_name='Average calculation time per m2 in seconds'),
        ),
    ]
