# Generated by Django 3.1 on 2025-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0043_component_average_calculation_time_per_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='estimated_finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated finish time'),
        ),
    ]
