# Generated by Django 3.1 on 2026-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0046_component_upload_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='upload_config',
            field=models.JSONField(blank=True, help_text='Optional JSON to override the default upload configuration for this component. Unspecified keys fall back to the global upload_config.json defaults. Example:\n{\n  "unit_folder": "unit_1",\n  "upload": {\n    "data_video": "DCIM",\n    "log": "GPS_LOG",\n    "calibration_video": null\n  },\n  "exclude": ["DCIM", "GPS_LOG"]\n}', null=True, verbose_name='Upload config'),
        ),
    ]
