# Generated by Django 3.1 on 2026-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0046_component_upload_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='charged_area_sq_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Charged area in sq km'),
        ),
        migrations.AddField(
            model_name='request',
            name='processed_area_sq_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Processed area in sq km'),
        ),
    ]
