# Generated by Django 3.1 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0047_auto_20260322_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='edge_chunk_data_api_required',
            field=models.BooleanField(default=False, verbose_name='Edge chunk data API access is required'),
        ),
    ]
