# Generated by Django 3.1 on 2026-03-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0047_auto_20260316_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='upload_config',
            field=models.JSONField(blank=True, help_text='Example:<br><pre>{\n  "unit_folder": "unit_1",\n  "upload": {\n    "data_video": "DCIM",\n    "log": "GPS_LOG",\n    "calibration_video": null\n  },\n  "exclude": ["DCIM", "GPS_LOG"]\n}</pre>', null=True, verbose_name='Upload config'),
        ),
    ]
