# Generated by Django 3.1 on 2026-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0048_auto_20260316_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='upload_config',
            field=models.JSONField(blank=True, help_text='Example:<br><pre>{\n  "unit_folder": "unit",\n  "upload": {\n    "data_video": "DCIM",\n    "log": "GPS_LOG",\n    "calibration_video": null\n  }\n}</pre>', null=True, verbose_name='Upload config'),
        ),
    ]
