# Generated by Django 3.1 on 2023-01-24 13:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0019_result_colormap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=225, verbose_name="Email's template")),
                ('subject', models.CharField(max_length=225, verbose_name="Email's subject")),
                ('recipient_email', models.EmailField(max_length=254)),
                ('context', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='publisher.result')),
            ],
        ),
    ]
