kind: PersistentVolume
apiVersion: v1
metadata:
  name: sip-data-pv
  namespace: sip
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sip-data-pvc
    namespace: sip