kind: PersistentVolume
apiVersion: v1
metadata:
  name: sip-data-pv
  namespace: sip
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.0.1
    path: "/data"
    readOnly: false
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sip-data-pvc
    namespace: sip