apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-volumeclaim
  namespace: sip
spec:
  # storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi