apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: prod
  labels:
    app: sip
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort:  31100
      protocol: TCP
      name: http
  selector:
    app: postgres