FROM python:3.8.15-slim

# Needed for geopanda&shapely to work
RUN apt-get update && \
    apt-get install -y \
    git \
    libspatialindex-dev

RUN mkdir /code
RUN mkdir /input
RUN mkdir /output
RUN mkdir /temp

WORKDIR /code
COPY ./ .

RUN pip install --upgrade pip ipython ipykernel papermill
RUN ipython kernel install --name "python3" --user
RUN pip install -r requirements_37.txt

ENTRYPOINT ["papermill", "./TCI_NDVI.ipynb", "./TCI_NDVI.ipynb"]
