# Generated by Django 3.1 on 2021-01-06 09:52

from django.db import migrations


def update_client_group_permissions(apps, schema_editor):
    """
    Add 'Can view JupyterNotebook'  permission for 'Client' group
    """
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model("auth", "Group")
    
    db_alias = schema_editor.connection.alias
    
    group, _ = group_model.objects.using(db_alias).get_or_create(name="Client")
    group.permissions.add(permission_model.objects.using(db_alias).get(codename='view_jupyternotebook'))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_notebook_perms_to_ds_engineer_group'),
    ]

    operations = [
        migrations.RunPython(update_client_group_permissions),
    ]
