# Generated by Django 3.1 on 2021-01-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_notebook_perms_to_client_group'),
    ]

    operations = [
    ]
