# Generated by Django 3.1 on 2021-01-11 16:51

from django.db import migrations


def add_permissions(apps, schema_editor):
    """
    Add permissions for Request model.
    :param apps:
    :param schema_editor:
    :return:
    """
    permission = apps.get_model("auth", "Permission")
    content_type = apps.get_model("contenttypes", "ContentType")
    
    model_def = apps.get_model("aoi", "Request")
    
    # Content type objects
    model_content_type = content_type.objects.get_for_model(model_def)
    
    db_alias = schema_editor.connection.alias
    
    permissions_data = [
        {"codename": "add_request", "name": "Can add Request",
         "content_type": model_content_type},
        {"codename": "change_request", "name": "Can change Request",
         "content_type": model_content_type},
        {"codename": "delete_request", "name": "Can delete Request",
         "content_type": model_content_type},
        {"codename": "view_request", "name": "Can view Request",
         "content_type": model_content_type},
    ]
    
    permission_list = []
    for permission_data in permissions_data:
        if not permission.objects.filter(codename=permission_data["codename"]).exists():
            permission_list.append(permission(codename=permission_data["codename"], name=permission_data["name"],
                                              content_type=permission_data["content_type"]))
    permission.objects.using(db_alias).bulk_create(permission_list)


def update_client_group_permissions(apps, schema_editor):
    """
    Add 'Can add Request' and 'Can view Request'  permissions for 'Client' group
    """
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model("auth", "Group")
    
    db_alias = schema_editor.connection.alias
    
    group, _ = group_model.objects.using(db_alias).get_or_create(name="Client")
    group.permissions.add(permission_model.objects.using(db_alias).get(codename='add_request'))
    group.permissions.add(permission_model.objects.using(db_alias).get(codename='view_request'))


def update_ds_engineer_group_permissions(apps, schema_editor):
    """
    Add 'Can add Request' and 'Can view Request' permissions for 'Data_science_engineer' group
    """
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model("auth", "Group")
    
    db_alias = schema_editor.connection.alias
    
    group, _ = group_model.objects.using(db_alias).get_or_create(name="Data_science_engineer")
    group.permissions.add(permission_model.objects.using(db_alias).get(codename='add_request'))
    group.permissions.add(permission_model.objects.using(db_alias).get(codename='view_request'))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_notebook_perms_to_client_group'),
    ]

    operations = [
        migrations.RunPython(add_permissions),
        migrations.RunPython(update_client_group_permissions),
        migrations.RunPython(update_ds_engineer_group_permissions),
    ]
