# Generated by Django 3.1 on 2021-01-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_request_perms'),
        ('user', '0007_add_new_perm_to_aoi'),
    ]

    operations = [
    ]
