# Generated by Django 3.1 on 2021-07-27 09:51

from django.db import migrations


def add_permissions(apps, schema_editor):
    """
    Add permissions for AoiType model.
    :param apps:
    :param schema_editor:
    :return:
    """
    app = 'aoi'
    model = 'AoiType'
    table_name = 'aoitype'
    permission = apps.get_model("auth", "Permission")
    content_type = apps.get_model("contenttypes", "ContentType")

    model_def = apps.get_model(app, model)

    # Content type objects
    model_content_type = content_type.objects.get_for_model(model_def)
    db_alias = schema_editor.connection.alias

    permissions_data = [
        {'codename': f'view_{table_name}', 'name': f'Can view {model}', 'content_type': model_content_type},
        {'codename': f'add_{table_name}', 'name': f'Can add {model}', 'content_type': model_content_type},
        {'codename': f'change_{table_name}', 'name': f'Can change {model}', 'content_type': model_content_type},
        {'codename': f'delete_{table_name}', 'name': f'Can delete {model}', 'content_type': model_content_type},
    ]

    permission_list = []
    for permission_data in permissions_data:
        if not permission.objects.filter(codename=permission_data["codename"]).exists():
            permission_list.append(permission(codename=permission_data["codename"], name=permission_data["name"],
                                              content_type=permission_data["content_type"]))
    permission.objects.using(db_alias).bulk_create(permission_list)


def update_client_group_permissions(apps, schema_editor):
    """
    Add 'Can view AoiType'  permission for 'Client' group
    """
    table_name = 'aoitype'
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model("auth", "Group")
    
    db_alias = schema_editor.connection.alias
    
    group, _ = group_model.objects.using(db_alias).get_or_create(name="Client")
    group.permissions.add(permission_model.objects.using(db_alias).get(codename=f'view_{table_name}'))


def update_ds_engineer_group_permissions(apps, schema_editor):
    """
    Add 'Can add AoiType' and 'Can view AoiType' permissions for 'Data_science_engineer' group
    """
    table_name = 'aoitype'
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model("auth", "Group")
    
    db_alias = schema_editor.connection.alias
    
    group, _ = group_model.objects.using(db_alias).get_or_create(name="Data_science_engineer")
    group.permissions.add(permission_model.objects.using(db_alias).get(codename=f'view_{table_name}'))
    

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20210115_1546'),
        ('aoi', '0014_aoi_type')
    ]

    operations = [
        migrations.RunPython(add_permissions),
        migrations.RunPython(update_client_group_permissions),
        migrations.RunPython(update_ds_engineer_group_permissions),
    ]
