# Generated by Django 3.1 on 2021-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_add_can_delete_results_perms_to_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_limit',
            field=models.IntegerField(default=10),
        ),
    ]
