# Generated by Django 3.1 on 2021-10-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_area_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_limit_ha',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
