# Generated by Django 3.1 on 2022-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_area_limit_ha_can_be_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planet_api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Planet API Key'),
        ),
    ]
