# Generated by Django 3.1 on 2023-02-15 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_planet_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_hold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='On hold'),
        ),
    ]
