# Generated by Django 3.1 on 2023-03-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_change_balance', 'Can change balance'),)},
        ),
    ]
