# Generated by Django 3.1 on 2023-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_add_balance_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rolled_back',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rolled back'),
        ),
    ]
