# Generated by Django 3.1 on 2023-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_transaction_rolled_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trial_end_notified',
            field=models.BooleanField(default=False, verbose_name='Is trial end notified'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial finished at'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial started at'),
        ),
    ]
