# Generated by Django 3.1 on 2023-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20230519_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_notification',
            field=models.BooleanField(default=True, verbose_name='Receive Notification'),
        ),
    ]
