# Generated by Django 3.1 on 2023-07-17 10:48

from django.db import migrations

def create_switch_row(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(name='remote_server_available', active=True)
    Switch.objects.create(name='our_server_is_overloaded_notification', active=False)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_receive_notification'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_switch_row),
    ]
