# Generated by Django 3.1 on 2023-07-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_transaction_error'),
        ('user', '0021_auto_20230717_1048'),
    ]

    operations = [
    ]
