# Generated by Django 3.1 on 2024-07-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_receive_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stone_google_folder',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Google bucket folder for stone detection'),
        ),
    ]
