# Generated by Django 3.1 on 2023-10-23 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_user_receive_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
