# Generated by Django 3.1 on 2023-10-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
