# Generated by Django 3.1 on 2024-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_stone_google_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='units_of_measurement',
            field=models.CharField(choices=[('km', 'Square Kilometers'), ('acre', 'Acres'), ('hectare', 'Hectares')], default='km', max_length=10),
        ),
    ]
