# Generated by Django 3.1 on 2024-08-29 09:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_units_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
