# Generated by Django 3.1 on 2026-04-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_stonesdetectionchunk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stonesdetectionchunk',
            name='unique_user_date_chunk_type',
        ),
        migrations.AlterUniqueTogether(
            name='stonesdetectionchunk',
            unique_together={('user', 'date', 'chunk', 'type')},
        ),
    ]
