# Generated by Django 3.1 on 2026-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20260407_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameratoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='cameratoken',
            name='cam_serial_num',
            field=models.CharField(max_length=128, unique=True, verbose_name='Camera serial number'),
        ),
    ]
