# Generated by Django 3.1 on 2026-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20260415_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonesdetectionchunk',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='Status'),
        ),
    ]
