# Generated by Django 3.1 on 2026-04-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoi', '0047_auto_20260322_1150'),
        ('user', '0036_devices_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stonesdetectionchunk',
            name='gpx_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones_chunk', to='aoi.request', verbose_name='GPX Request'),
        ),
    ]
