# Generated by Django 3.1 on 2026-08-19 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_user_stones_storage_edge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgePrediction',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(default='1', max_length=10)),
                ('gprmc', models.CharField(blank=True, help_text='Raw NMEA string', max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_since_boot_sec', models.FloatField(blank=True, null=True)),
                ('predictions', models.JSONField(blank=True, default=list, help_text='Bounding boxes and confidences')),
                ('image_path', models.CharField(blank=True, help_text='Relative GCS path to image', max_length=512, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='user.stonesdetectionchunk')),
            ],
            options={
                'verbose_name': 'Edge Prediction',
                'verbose_name_plural': 'Edge Predictions',
            },
        ),
        migrations.CreateModel(
            name='EdgeCoverage',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(default='1', max_length=10)),
                ('gprmc', models.CharField(blank=True, help_text='Raw NMEA string', max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, help_text='Relative GCS path to image', max_length=512, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='user.stonesdetectionchunk')),
            ],
            options={
                'verbose_name': 'Edge Coverage',
                'verbose_name_plural': 'Edge Coverages',
            },
        ),
    ]
