# Generated by Django 3.1 on 2026-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_edgecoverage_edgeprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgecoverage',
            name='captured_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='UTC timestamp parsed from the GPRMC datestamp/timestamp',
            ),
        ),
        migrations.AddField(
            model_name='edgecoverage',
            name='speed',
            field=models.FloatField(
                blank=True, null=True,
                help_text='Speed over ground in knots, parsed from GPRMC spd_over_grnd',
            ),
        ),
        migrations.AddField(
            model_name='edgeprediction',
            name='captured_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='UTC timestamp parsed from the GPRMC datestamp/timestamp',
            ),
        ),
        migrations.AddField(
            model_name='edgeprediction',
            name='speed',
            field=models.FloatField(
                blank=True, null=True,
                help_text='Speed over ground in knots, parsed from GPRMC spd_over_grnd',
            ),
        ),
    ]
