# Generated by Django 3.1 on 2026-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_add_captured_at_speed_to_edge_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgecoverage',
            name='serial',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='edgeprediction',
            name='serial',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='edgecoverage',
            index=models.Index(fields=['serial', 'captured_at'], name='edgecov_serial_captured_idx'),
        ),
        migrations.AddIndex(
            model_name='edgecoverage',
            index=models.Index(fields=['serial', 'created_at'], name='edgecov_serial_created_idx'),
        ),
        migrations.AddIndex(
            model_name='edgeprediction',
            index=models.Index(fields=['serial', 'captured_at'], name='edgepred_serial_captured_idx'),
        ),
        migrations.AddIndex(
            model_name='edgeprediction',
            index=models.Index(fields=['serial', 'created_at'], name='edgepred_serial_created_idx'),
        ),
    ]
