# Generated by Django 3.1 on 2026-09-02 09:12

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_add_composite_indexes_to_edge_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Regina', help_text='IANA timezone name, e.g. America/Regina', max_length=64, validators=[user.models.validate_timezone], verbose_name='Account timezone'),
        ),
    ]
